# Generated by Django 2.0.6 on 2018-06-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_remove_user_username'),
        ('project_manager', '0002_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='login_registration.User'),
            preserve_default=False,
        ),
    ]
