# Generated by Django 2.0.6 on 2018-06-18 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_remove_user_username'),
        ('bill_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='user',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='login_registration.User'),
            preserve_default=False,
        ),
    ]
